version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartscrape_api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    ports:
      - "8000:8000"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartscrape_worker
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
    command: >
      sh -c "python -m app.workers.worker"

  redis:
    image: redis:7-alpine
    container_name: smartscrape_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
